/*
The Fibonacci sequence is the series of numbers 0, 1, 1, 2, 3, 5, 8, .... 
Formally, it can be expressed as: 
    fib0 = 0 
    fib1 = 1 
    fibn = fibn−1 + fibn−2 
Write a multithreaded program that generates the Fibonacci sequence. This 
program should work as follows: On the command line, the user will enter the 
number of Fibonacci numbers that the program is to generate. The program 
will then create a separate thread that will generate the Fibonacci numbers, 
placing the sequence in data that can be shared by the threads (an array is 
probably the most convenient data structure). When the thread finishes 
execution, the parent thread will output the sequence generated by the child 
thread. Because the parent thread cannot begin outputting the Fibonacci 
sequence until the child thread finishes, the parent thread will have to wait for 
the child thread to finish.
*/

/*
    gcc Question_21.c -o fib_thread -pthread
    ./fib_thread 10
*/


#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>  

int count;
int *array;

void *generate_fibonacci(void *arg) {
    if (count >= 1) array[0] = 0;
    if (count >= 2) array[1] = 1;

    for (int i = 2; i < count; i++) {
        array[i] = array[i - 2] + array[i - 1];
    }

    pthread_exit(NULL);
}

int main(int argc, char *argv[]) {
    pthread_t thread;

    if (argc != 2) {
        printf("Usage: %s <number_of_terms>\n", argv[0]);
        return 1;
    }

    count = atoi(argv[1]);

    if (count <= 0) {
        printf("Number of terms must be positive.\n");
        return 1;
    }

    array = (int *)malloc(sizeof(int) * count);

    // Create and wait for the thread
    pthread_create(&thread, NULL, generate_fibonacci, NULL);
    pthread_join(thread, NULL);

    printf("The Fibonacci series is:\n");
    for (int i = 0; i < count; i++) {
        printf("%d ", array[i]);
    }
    printf("\n");

    free(array);
    return 0;
}

